// Generates src/lib/techIconPaths.ts with ONLY the SVG path of each icon (simple-icons, CC0).
// Importing the full simple-icons objects adds their duplicated `svg` and metadata to the bundle.
// Usage: npm run icons  (after changing the list or updating simple-icons)
import { writeFileSync } from "node:fs";
import * as icons from "simple-icons";

const SLUGS = [
  "angular", "apachemaven", "django", "docker", "dotnet", "express", "fastapi", "fastify", "flask", "gin",
  "githubactions", "go", "gradle", "hibernate", "htmx", "javascript", "jest", "jquery", "junit5", "kotlin", "koa",
  "kubernetes", "laravel", "mariadb", "mongodb", "mongoose", "mysql", "nestjs", "nextdotjs", "npm", "nuxt", "openjdk",
  "php", "postgresql", "prisma", "pytest", "python", "quarkus", "react", "redis", "rubyonrails", "ruby", "rust",
  "sequelize", "solid", "springboot", "sqlalchemy", "sqlite", "svelte", "symfony", "terraform", "typeorm", "typescript",
  "vite", "vitest", "vuedotjs", "webpack",
];

const bySlug = new Map(Object.values(icons).filter((icon) => icon && icon.slug).map((icon) => [icon.slug, icon.path]));
const missing = SLUGS.filter((slug) => !bySlug.has(slug));
if (missing.length) {
  console.error(`Iconos inexistentes en simple-icons: ${missing.join(", ")}`);
  process.exit(1);
}
const body = SLUGS.map((slug) => `  ${JSON.stringify(slug)}: ${JSON.stringify(bySlug.get(slug))},`).join("\n");
writeFileSync(
  new URL("../src/lib/techIconPaths.ts", import.meta.url),
  `// Generated by scripts/tech-icons.mjs from simple-icons (CC0). Do not edit by hand.\n` +
    `/** SVG path (viewBox 0 0 24 24) of each technology, by slug. */\n` +
    `export const TECH_ICONS: Record<string, string> = {\n${body}\n};\n`,
);
console.log(`techIconPaths.ts: ${SLUGS.length} iconos`);
